# Generated by Django 3.1.7 on 2021-10-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20211005_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Cleaner', 'Cleaner'), ('Salon', 'Salon'), ('Laundry', 'Laundry'), ('Delivery', 'Delivery'), ('Plumber', 'Plumber')], default='Delivery', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('ServiceProvider', 'ServiceProvider')], default='Customer', max_length=15),
        ),
    ]
