# Generated by Django 3.2.7 on 2021-10-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_0002_auto_20211004_1609_0002_profile_bio'),
        ('authentication', '0004_auto_20211008_1215'),
    ]

    operations = [
    ]
