# Generated by Django 3.1.7 on 2021-10-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20211005_0713'),
        ('authentication', '0007_auto_20211011_0749'),
    ]

    operations = [
    ]
