# Generated by Django 3.1.7 on 2021-10-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20211011_1933'),
        ('authentication', '0008_merge_20211011_1122'),
    ]

    operations = [
    ]
