# Generated by Django 3.2.7 on 2021-10-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211004_1609'),
        ('authentication', '0002_profile_bio'),
    ]

    operations = [
    ]
