# Generated by Django 3.1.7 on 2021-10-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_bio'),
        ('authentication', '0002_auto_20211004_1609'),
    ]

    operations = [
    ]
