# Generated by Django 3.1.7 on 2021-10-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20211005_0621'),
        ('authentication', '0005_merge_20211009_0652'),
    ]

    operations = [
    ]
