# Generated by Django 3.2.7 on 2021-10-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20211011_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('Customer', 'Customer'), ('ServiceProvider', 'ServiceProvider')], default='Customer', max_length=15),
        ),
    ]
