# Generated by Django 3.1.7 on 2021-10-04 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('MinPrice', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField(default=100)),
                ('FromLocation', models.TextField()),
                ('Description', models.TextField()),
                ('QueuedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('AcceptedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('CanceledTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('OrderFinishedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('CompletedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ServiceType', models.CharField(choices=[('Electrician', 'Electrician'), ('Cleaner', 'Cleaner'), ('Salon', 'Salon'), ('Laundry', 'Laundry'), ('Delivery', 'Delivery'), ('Plumber', 'Plumber')], default='Laundry', max_length=15)),
                ('PreferredTime', models.CharField(choices=[('Anytime', 'Anytime'), ('10AM-12PM', '10AM-12PM'), ('2PM-5PM', '2PM-5PM'), ('5PM-8PM', '5PM-8PM')], default='Anytime', max_length=15)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
                ('ServiceProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceProvider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
