# Generated by Django 3.1.7 on 2021-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceType', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('MinPrice', models.IntegerField(default=20)),
            ],
        ),
    ]
