# Generated by Django 3.1.7 on 2021-09-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='ServiceType',
            new_name='ServiceName',
        ),
    ]
