# Generated by Django 3.1.7 on 2021-09-30 11:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ucnitk', '0002_auto_20210930_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.IntegerField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('FromLocation', models.TextField()),
                ('Description', models.TextField()),
                ('QueuedTime', models.DateTimeField(default=datetime.datetime(2021, 9, 30, 11, 49, 42, 605251, tzinfo=utc))),
                ('AcceptedTime', models.DateTimeField(null=True)),
                ('CanceledTime', models.DateTimeField(null=True)),
                ('OrderFinishedTime', models.DateTimeField(null=True)),
                ('CompletedTime', models.DateTimeField(null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
                ('ServiceProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ServiceProvider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
