# Generated by Django 3.1.7 on 2021-10-09 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ucnitk', '0003_auto_20211008_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceType', models.CharField(choices=[('Electrician', 'Electrician'), ('Cleaner', 'Cleaner'), ('Salon', 'Salon'), ('Laundry', 'Laundry'), ('Delivery', 'Delivery'), ('Plumber', 'Plumber')], default='Laundry', max_length=15)),
                ('rating', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1)),
                ('review', models.CharField(max_length=250)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_Customer', to=settings.AUTH_USER_MODEL)),
                ('ServiceProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_ServiceProvider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
