# Generated by Django 3.1.7 on 2021-10-03 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='QueuedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 12, 1, 34, 121094, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='MinPrice',
            field=models.IntegerField(default=5),
        ),
    ]
