# Generated by Django 3.1.7 on 2021-10-03 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0004_auto_20211003_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='QueuedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 19, 9, 51, 747548, tzinfo=utc)),
        ),
    ]
