# Generated by Django 3.1.7 on 2021-10-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0005_auto_20211011_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
