# Generated by Django 3.1.7 on 2021-10-04 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0005_auto_20211003_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PreferredTime',
            field=models.CharField(choices=[('Anytime', 'Anytime'), ('10AM-12PM', '10AM-12PM'), ('2PM-5PM', '2PM-5PM'), ('5PM-8PM', '5PM-8PM')], default='Anytime', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='ServiceType',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Cleaner', 'Cleaner'), ('Salon', 'Salon'), ('Laundry', 'Laundry'), ('Delivery', 'Delivery'), ('Plumber', 'Plumber')], default='Laundry', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='QueuedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 10, 32, 3, 125639, tzinfo=utc)),
        ),
    ]
