# Generated by Django 3.1.7 on 2021-10-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0006_auto_20211004_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
