# Generated by Django 3.1.7 on 2021-10-14 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ucnitk', '0007_auto_20211014_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ServiceProvider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ServiceProvider', to=settings.AUTH_USER_MODEL),
        ),
    ]
