# Generated by Django 3.1.7 on 2021-10-04 10:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ucnitk', '0007_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('FromLocation', models.TextField()),
                ('Description', models.TextField()),
                ('QueuedTime', models.DateTimeField(default=datetime.datetime(2021, 10, 4, 10, 56, 17, 165821, tzinfo=utc))),
                ('AcceptedTime', models.DateTimeField(null=True)),
                ('CanceledTime', models.DateTimeField(null=True)),
                ('OrderFinishedTime', models.DateTimeField(null=True)),
                ('CompletedTime', models.DateTimeField(null=True)),
                ('ServiceType', models.CharField(choices=[('Electrician', 'Electrician'), ('Cleaner', 'Cleaner'), ('Salon', 'Salon'), ('Laundry', 'Laundry'), ('Delivery', 'Delivery'), ('Plumber', 'Plumber')], default='Laundry', max_length=15)),
                ('PreferredTime', models.CharField(choices=[('Anytime', 'Anytime'), ('10AM-12PM', '10AM-12PM'), ('2PM-5PM', '2PM-5PM'), ('5PM-8PM', '5PM-8PM')], default='Anytime', max_length=15)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
                ('ServiceProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ServiceProvider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
