# Generated by Django 3.2.7 on 2021-10-14 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0009_help_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='AddedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
