# Generated by Django 3.1.7 on 2021-10-04 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0009_auto_20211004_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='QueuedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 10, 59, 29, 632280, tzinfo=utc)),
        ),
    ]
