# Generated by Django 3.1.7 on 2021-10-04 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0010_auto_20211004_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='QueuedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 11, 0, 30, 834161, tzinfo=utc)),
        ),
    ]
