# Generated by Django 3.1.7 on 2021-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0011_auto_20211004_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='QueuedTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
