# Generated by Django 3.2.7 on 2021-10-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0011_auto_20211015_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='I_Status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Pending', 'Pending')], default='Pending', max_length=15),
        ),
    ]
