# Generated by Django 3.2.7 on 2021-10-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0012_help_i_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='I_type',
            field=models.CharField(choices=[('Order Not being Accepted/Delivered', 'Order Not being Accepted/Delivered'), ('Issue With Service Provider', 'Issue With Service Provider'), ('Order Says Delivered but have not recieved anything', 'Order Says Delivered but have not recieved anything'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
