# Generated by Django 3.2.7 on 2021-10-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0013_help_i_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='I_details',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
