# Generated by Django 3.2.7 on 2021-10-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0014_help_i_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='help/')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucnitk.help')),
            ],
        ),
    ]
