# Generated by Django 3.1.7 on 2021-10-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0016_alter_images_image'),
        ('ucnitk', '0009_auto_20211014_1702'),
    ]

    operations = [
    ]
