# Generated by Django 3.1.7 on 2021-10-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucnitk', '0018_auto_20211016_0741'),
        ('ucnitk', '0018_auto_20211016_1252'),
    ]

    operations = [
    ]
